/*
This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcodc", return ''
*/

"use strict";

function createCharacterDictionary(inputString) {
  let charactersInInputString = new Map();

  for (let i = 0; i < inputString.length; i++) {
    if (!charactersInInputString.has(inputString[i])) {
      charactersInInputString.set(inputString[i], 1);
    } else {
      charactersInInputString.set(
        inputString[i],
        charactersInInputString.get(inputString[i]) + 1
      );
    }
  }

  return charactersInInputString;
}

function checkForMissingCharacter(characterDictionary, inputString) {
  for (let i = 0; i < inputString.length; i++) {
    if (!characterDictionary.has(inputString[i])) {
      return inputString[i];
    }
  }
}

function checkForAddedCharacter(characterDictionary, inputString) {
  for (let i = 0; i < inputString.length; i++) {
    characterDictionary.set(
      inputString[i],
      characterDictionary.get(inputString[i]) - 1
    );
    if (characterDictionary.get(inputString[i]) == -1) {
      return inputString[i];
    }
  }
}

function spotTheDifference(firstString, secondString) {
  let charactersInFirstString = createCharacterDictionary(firstString);

  let missingCharacter = checkForMissingCharacter(
    charactersInFirstString,
    secondString
  );

  if (missingCharacter) return missingCharacter;

  let addedCharacter = checkForAddedCharacter(
    charactersInFirstString,
    secondString
  );

  if (addedCharacter) return addedCharacter;

  return "";
}

console.log(spotTheDifference("foobar", "barfoot"));
console.log(spotTheDifference("ide", "idea"));
console.log(spotTheDifference("coding", "ingcodc"));
